name: Testes Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Testes_Backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Open Folder
        run: cd busca-keywords/
        
      - name: Run Tests
        run: python pytest
