name: Testes Backend

on:
  push:
    branches: [ all ]
  pull_request:
    branches: [ main ]

jobs:
  Testes_Backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.14'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Tests
        run: |
          cd busca-keywords/
          python -m pytest
